#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/alemay/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#gkrellm & 
workrave &
xfce4-power-manager &
volumeicon &
xscreensaver -verbose -log /home/alemay/.logs/xscreen-log.txt &
nm-applet &
shutter --min_at_startup &
conky -c /home/alemay/.conkyrc -a top_right &
conky -c /home/alemay/.conky/conky_rings &
dropbox start &
nitrogen --restore &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/alemay/.fluxbox/log"
